# Generated by Django 5.0.7 on 2026-08-23 04:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del plan')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio mensual')),
                ('max_invoices_per_month', models.PositiveIntegerField(default=0, verbose_name='Máx. facturas por mes (0 = ilimitado)')),
                ('max_users', models.PositiveIntegerField(default=0, verbose_name='Máx. usuarios (0 = ilimitado)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Duración (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price'],
                'permissions': (('view_plan', 'Can view Plan'), ('add_plan', 'Can add Plan'), ('change_plan', 'Can change Plan'), ('delete_plan', 'Can delete Plan')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='trial', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pos.company', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'permissions': (('view_subscription', 'Can view Suscripción'), ('add_subscription', 'Can add Suscripción'), ('change_subscription', 'Can change Suscripción'), ('delete_subscription', 'Can delete Suscripción')),
                'default_permissions': (),
            },
        ),
    ]
