# Generated by Django 5.0.7 on 2026-06-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Ingrese un nombre', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(help_text='Ingrese un número de cédula o RUC', max_length=13, verbose_name='Número de cédula o RUC'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(help_text='Ingrese un nombre', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Ingrese un código', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(help_text='Ingrese un email', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='mobile',
            field=models.CharField(help_text='Ingrese un número de teléfono celular', max_length=10, verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Ingrese un nombre', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.CharField(help_text='Ingrese un RUC', max_length=13, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.CharField(help_text='Ingrese un número de factura', max_length=8, verbose_name='Número de factura'),
        ),
    ]
